//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HockeyApp.Resources
{
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HockeyApp.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string AppCenter
        {
            get
            {
                return ResourceManager.GetString("AppCenter", resourceCulture);
            }
        }

        public static string SignInLabel
        {
            get
            {
                return ResourceManager.GetString("SignInLabel", resourceCulture);
            }
        }

        public static string VisualStudio
        {
            get
            {
                return ResourceManager.GetString("VisualStudio", resourceCulture);
            }
        }

        public static string LoginFailedLabel
        {
            get
            {
                return ResourceManager.GetString("LoginFailedLabel", resourceCulture);
            }
        }

        public static string LoginFailedMessageLabel
        {
            get
            {
                return ResourceManager.GetString("LoginFailedMessageLabel", resourceCulture);
            }
        }

        public static string OkLabel
        {
            get
            {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }

        public static string CancelLabel
        {
            get
            {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }

        public static string LoginErrorLabel
        {
            get
            {
                return ResourceManager.GetString("LoginErrorLabel", resourceCulture);
            }
        }

        public static string InvalidUsernameLabel
        {
            get
            {
                return ResourceManager.GetString("InvalidUsernameLabel", resourceCulture);
            }
        }

        public static string InvalidPasswordLabel
        {
            get
            {
                return ResourceManager.GetString("InvalidPasswordLabel", resourceCulture);
            }
        }

        public static string GeneralErrorLabel
        {
            get
            {
                return ResourceManager.GetString("GeneralErrorLabel", resourceCulture);
            }
        }

        public static string GeneralErrorMessageLabel
        {
            get
            {
                return ResourceManager.GetString("GeneralErrorMessageLabel", resourceCulture);
            }
        }

        public static string UnauthorizedLabel
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedLabel", resourceCulture);
            }
        }

        public static string UnauthorizedMessageLabel
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedMessageLabel", resourceCulture);
            }
        }

        public static string LatestLabel
        {
            get
            {
                return ResourceManager.GetString("LatestLabel", resourceCulture);
            }
        }

        public static string HistoryLabel
        {
            get
            {
                return ResourceManager.GetString("HistoryLabel", resourceCulture);
            }
        }

        public static string ReleaseLabel
        {
            get
            {
                return ResourceManager.GetString("ReleaseLabel", resourceCulture);
            }
        }

        public static string ReleaseNotesLabel
        {
            get
            {
                return ResourceManager.GetString("ReleaseNotesLabel", resourceCulture);
            }
        }

        public static string PickAnOrgMessageLabel
        {
            get
            {
                return ResourceManager.GetString("PickAnOrgMessageLabel", resourceCulture);
            }
        }

        public static string AllMyAppsLabel
        {
            get
            {
                return ResourceManager.GetString("AllMyAppsLabel", resourceCulture);
            }
        }

        public static string DoneLabel
        {
            get
            {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }

        public static string InstallLabel
        {
            get
            {
                return ResourceManager.GetString("InstallLabel", resourceCulture);
            }
        }

        public static string SearchByAppNameLabel
        {
            get
            {
                return ResourceManager.GetString("SearchByAppNameLabel", resourceCulture);
            }
        }

        public static string NoAppsFoundLabel
        {
            get
            {
                return ResourceManager.GetString("NoAppsFoundLabel", resourceCulture);
            }
        }

        public static string NoAppsAvailableLabel
        {
            get
            {
                return ResourceManager.GetString("NoAppsAvailableLabel", resourceCulture);
            }
        }

        public static string SearchReleasesLabel
        {
            get
            {
                return ResourceManager.GetString("SearchReleasesLabel", resourceCulture);
            }
        }

        public static string DowngradeNotAllowedLabel
        {
            get
            {
                return ResourceManager.GetString("DowngradeNotAllowedLabel", resourceCulture);
            }
        }

        public static string InstallingLabel
        {
            get
            {
                return ResourceManager.GetString("InstallingLabel", resourceCulture);
            }
        }

        public static string InstallingLabel2
        {
            get
            {
                return ResourceManager.GetString("InstallingLabel2", resourceCulture);
            }
        }

        public static string InstallingLabel3
        {
            get
            {
                return ResourceManager.GetString("InstallingLabel3", resourceCulture);
            }
        }

        public static string InstallingLabel4
        {
            get
            {
                return ResourceManager.GetString("InstallingLabel4", resourceCulture);
            }
        }

        public static string CustomUriScheme
        {
            get
            {
                return ResourceManager.GetString("CustomUriScheme", resourceCulture);
            }
        }

        public static string DeviceInfoLabel
        {
            get
            {
                return ResourceManager.GetString("DeviceInfoLabel", resourceCulture);
            }
        }

        public static string ModelLabel
        {
            get
            {
                return ResourceManager.GetString("ModelLabel", resourceCulture);
            }
        }

        public static string VersionLabel
        {
            get
            {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }

        public static string PhoneIdLabel
        {
            get
            {
                return ResourceManager.GetString("PhoneIdLabel", resourceCulture);
            }
        }

        public static string RegisterDevicelLabel
        {
            get
            {
                return ResourceManager.GetString("RegisterDevicelLabel", resourceCulture);
            }
        }

        public static string RegisterDeviceMessage
        {
            get
            {
                return ResourceManager.GetString("RegisterDeviceMessage", resourceCulture);
            }
        }

        public static string SignOutLabel
        {
            get
            {
                return ResourceManager.GetString("SignOutLabel", resourceCulture);
            }
        }

        public static string NetworkErrorLabel
        {
            get
            {
                return ResourceManager.GetString("NetworkErrorLabel", resourceCulture);
            }
        }

        public static string NetworkErrorMessageLabel
        {
            get
            {
                return ResourceManager.GetString("NetworkErrorMessageLabel", resourceCulture);
            }
        }

        public static string PlatformLabel
        {
            get
            {
                return ResourceManager.GetString("PlatformLabel", resourceCulture);
            }
        }

        public static string OrgsLabel
        {
            get
            {
                return ResourceManager.GetString("OrgsLabel", resourceCulture);
            }
        }

        public static string PlatformSelectionMessage
        {
            get
            {
                return ResourceManager.GetString("PlatformSelectionMessage", resourceCulture);
            }
        }

        public static string RefreshLabel
        {
            get
            {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }

        public static string EditProfileButton
        {
            get
            {
                return ResourceManager.GetString("EditProfileButton", resourceCulture);
            }
        }

        public static string ReRegisterDeviceLabel
        {
            get
            {
                return ResourceManager.GetString("ReRegisterDeviceLabel", resourceCulture);
            }
        }

        public static string AboutLabel
        {
            get
            {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }

        public static string AppVersionLabel
        {
            get
            {
                return ResourceManager.GetString("AppVersionLabel", resourceCulture);
            }
        }

        public static string AccountSignUpLabel
        {
            get
            {
                return ResourceManager.GetString("AccountSignUpLabel", resourceCulture);
            }
        }

        public static string ForgotPasswordLabel
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordLabel", resourceCulture);
            }
        }

        public static string DetailsLabel
        {
            get
            {
                return ResourceManager.GetString("DetailsLabel", resourceCulture);
            }
        }

        public static string AppDetailsLabel
        {
            get
            {
                return ResourceManager.GetString("AppDetailsLabel", resourceCulture);
            }
        }

        public static string EmailLabel
        {
            get
            {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }

        public static string PasswordLabel
        {
            get
            {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }

        public static string FeedbackCommentsSectionQuestionLabel
        {
            get
            {
                return ResourceManager.GetString("FeedbackCommentsSectionQuestionLabel", resourceCulture);
            }
        }

        public static string FeedbackHeaderLabel
        {
            get
            {
                return ResourceManager.GetString("FeedbackHeaderLabel", resourceCulture);
            }
        }

        public static string FeedbackNotLikelyLabel
        {
            get
            {
                return ResourceManager.GetString("FeedbackNotLikelyLabel", resourceCulture);
            }
        }

        public static string FeedbackSubHeaderQuestionLabel
        {
            get
            {
                return ResourceManager.GetString("FeedbackSubHeaderQuestionLabel", resourceCulture);
            }
        }

        public static string FeedbackVeryLikelyLabel
        {
            get
            {
                return ResourceManager.GetString("FeedbackVeryLikelyLabel", resourceCulture);
            }
        }

        public static string NextButton
        {
            get
            {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }

        public static string SubmitFeedbackButton
        {
            get
            {
                return ResourceManager.GetString("SubmitFeedbackButton", resourceCulture);
            }
        }

        public static string FeedbackThankYouLabel
        {
            get
            {
                return ResourceManager.GetString("FeedbackThankYouLabel", resourceCulture);
            }
        }

        public static string AllApps
        {
            get
            {
                return ResourceManager.GetString("AllApps", resourceCulture);
            }
        }

        public static string MyApps
        {
            get
            {
                return ResourceManager.GetString("MyApps", resourceCulture);
            }
        }

        public static string Android
        {
            get
            {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }

        public static string iOS
        {
            get
            {
                return ResourceManager.GetString("iOS", resourceCulture);
            }
        }

        public static string Windows
        {
            get
            {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }

        public static string FeedbackThankYouSubLabel
        {
            get
            {
                return ResourceManager.GetString("FeedbackThankYouSubLabel", resourceCulture);
            }
        }

        public static string NoReleasesFoundLabel
        {
            get
            {
                return ResourceManager.GetString("NoReleasesFoundLabel", resourceCulture);
            }
        }

        public static string PrivacyPolicyLabel
        {
            get
            {
                return ResourceManager.GetString("PrivacyPolicyLabel", resourceCulture);
            }
        }

        public static string LegalTermsLabel
        {
            get
            {
                return ResourceManager.GetString("LegalTermsLabel", resourceCulture);
            }
        }

        public static string PrivacyPolicyUrl
        {
            get
            {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }

        public static string TermsAndConditionsUrl
        {
            get
            {
                return ResourceManager.GetString("TermsAndConditionsUrl", resourceCulture);
            }
        }

        public static string NoReleasesFilteredFoundLabel
        {
            get
            {
                return ResourceManager.GetString("NoReleasesFilteredFoundLabel", resourceCulture);
            }
        }

        public static string ReportAnIssueLabel
        {
            get
            {
                return ResourceManager.GetString("ReportAnIssueLabel", resourceCulture);
            }
        }
    }
}
